############################# Default configuration ########################
# baseURL = "https://demo.gethugothemes.com/agico/"
title = "Agico | App Landing Hugo Template"
theme = "agico-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "agico" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
publishDir = "docs"

################################### Outputs #################################
# hugo outputs
[outputs]
home = [ "HTML", "JSON", "RSS"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


########################### Default parameters ###########################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "9567 Turner Trace Apt. 466 North Willie, BC C3G8A4"
mobile = "+211234565523"
email = "info@agico.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "Your ID"
# main sections
mainSections = ["blog"]


################################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"

# site variables
[params.variables]
primary_color = "#007ac7"
secondary_color = "#00e0d8"
bg_secondary = "#15192b"
text_dark = "#242f3e"
text_color = "#8b8e93"
text_light = "#d4dae3"
text_color_light = "#959595"
border_color = "#2d3041"
bg_gradient_primary = "linear-gradient(134deg, #00a4db 0%, #00269e 100%)"
bg_gradient_secondary = "linear-gradient( 80deg, rgb(0,48,204) 0%, rgb(0,164,219) 100%)"
btn_gradient_primary = "linear-gradient(45deg, rgb(0, 168, 244) 0%, rgb(2, 209, 161) 100%)"
black = "#000"
white = "#fff"
gray = "#8b8e93"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Poppins:wght@300;400;500;600;700"
primary_font_type = "sans-serif" # [serif/sans-serif]
secondary_font = "Open Sans:wght@300;400;600;700;800"
secondary_font_type = "sans-serif" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif"

# Navigation button
[params.navigation_button]
enable = true
label = "sign up"
link = "#"

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
map_marker_label = "Agico"
map_zoom = 17

########################### social icon ############################
[[params.social]]
icon = "fab fa-facebook"
link = "https://facebook.com/themefisher"

[[params.social]]
icon = "fab fa-twitter"
link = "https://twitter.com/themefisher"

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/themefisher"

[[params.social]]
icon = "fab fa-instagram"
link = "https://instagram.com/themefisher"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"


############################ English navigation

# main menu    
[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2
  
[[Languages.en.menu.main]]
name = "Service"
URL = "service"
weight = 3

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 5

[[Languages.en.menu.main]]
weight = 6
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Pricing"
  URL = "pricing"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Career"
  URL = "career"
  
  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Team"
  URL = "team"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"
  
  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Changelog"
  URL = "changelog"

#Footer menu
[[Languages.en.menu.footer]]
name = "Company History"
URL = "about"

[[Languages.en.menu.footer]]
name = "About us"
URL = "about"

[[Languages.en.menu.footer]]
name = "Contact us"
URL = "contact"

[[Languages.en.menu.footer]]
name = "Services"
URL = "service"

[[Languages.en.menu.footer]]
name = "Privacy Policy"
URL = "#"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"


############################ French navigation

# main menu    
[[Languages.fr.menu.main]]
name = "About"
URL = "about"
weight = 2
  
[[Languages.fr.menu.main]]
name = "Service"
URL = "service"
weight = 3

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.fr.menu.main]]
name = "Contact"
URL = "contact"
weight = 5

[[Languages.fr.menu.main]]
weight = 6
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Pricing"
  URL = "pricing"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Career"
  URL = "career"
  
  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Team"
  URL = "team"
  
  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"
  
  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Changelog"
  URL = "changelog"

#Footer menu
[[Languages.fr.menu.footer]]
name = "Company History"
URL = "about"

[[Languages.fr.menu.footer]]
name = "About us"
URL = "about"

[[Languages.fr.menu.footer]]
name = "Contact us"
URL = "contact"

[[Languages.fr.menu.footer]]
name = "Services"
URL = "service"

[[Languages.fr.menu.footer]]
name = "Privacy Policy"
URL = "#"